from __future__ import annotations
from typing import Protocol, Any
import pyarrow as pa


class ObjectStoragePlugin(Protocol):
    def put(self, bucket: str, key: str, body: bytes) -> None: ...
    def get(self, bucket: str, key: str) -> bytes: ...
    def delete(self, bucket: str, key: str) -> None: ...
    def exists(self, bucket: str, key: str) -> bool: ...
    def list(self, bucket: str, prefix: str = "", limit: int = 1000) -> list[str]: ...
    def ensure_bucket(self, bucket: str) -> None: ...
    def health(self) -> bool: ...


class TabularStoragePlugin(Protocol):
    def create_table(self, namespace: str, table: str, schema: pa.Schema, location: str | None = None) -> str: ...
    def table_exists(self, namespace: str, table: str) -> bool: ...
    def list_tables(self, namespace: str) -> list[str]: ...
    def list_namespaces(self) -> list[str]: ...
    def ensure_namespace(self, namespace: str) -> None: ...
    def append(self, namespace: str, table: str, data: pa.Table) -> int: ...
    def overwrite(self, namespace: str, table: str, data: pa.Table) -> int: ...
    def scan(self, namespace: str, table: str, columns: list[str] | None = None,
             filter: str | None = None, limit: int | None = None) -> pa.Table: ...
    def describe(self, namespace: str, table: str) -> dict: ...
    def drop_table(self, namespace: str, table: str) -> None: ...
    def health(self) -> bool: ...


class VectorStoragePlugin(Protocol):
    def create_table(self, db: str, name: str, data: pa.Table, mode: str = "overwrite") -> None: ...
    def table_exists(self, db: str, name: str) -> bool: ...
    def list_tables(self, db: str) -> list[str]: ...
    def add(self, db: str, name: str, data: pa.Table) -> int: ...
    def search(self, db: str, name: str, query_vec: list[float],
               top_k: int = 5, filter: str | None = None) -> list[dict]: ...
    def count_rows(self, db: str, name: str) -> int: ...
    def describe(self, db: str, name: str) -> dict: ...
    def health(self) -> bool: ...


class KVStoragePlugin(Protocol):
    def get(self, db: int, key: str) -> str | None: ...
    def set(self, db: int, key: str, value: str, ttl: int | None = None) -> None: ...
    def delete(self, db: int, key: str) -> bool: ...
    def scan(self, db: int, pattern: str = "*", limit: int = 1000) -> list[str]: ...
    def health(self) -> bool: ...


class GraphStoragePlugin(Protocol):
    def add_node(self, graph: str, node_id: str, label: str, properties: dict, tenant_id: str) -> None: ...
    def add_edge(self, graph: str, edge_id: str, src: str, dst: str,
                 rel: str, properties: dict, tenant_id: str) -> None: ...
    def query_nodes(self, graph: str, tenant_id: str, label: str | None = None) -> list[dict]: ...
    def query_edges(self, graph: str, src: str, tenant_id: str) -> list[dict]: ...
    def delete_node(self, graph: str, node_id: str, tenant_id: str) -> None: ...
    def health(self) -> bool: ...


class MetadataStorePlugin(Protocol):
    def create_tenant(self, tenant_id: str, name: str) -> dict: ...
    def update_tenant(self, tenant_id: str, name: str | None = None, status: str | None = None) -> dict: ...
    def delete_tenant(self, tenant_id: str) -> dict: ...
    def list_tenants(self) -> dict: ...
    def create_user(self, username: str, tenant_id: str, role: str = "user") -> dict: ...
    def update_user(self, user_id: str, username: str | None = None,
                    role: str | None = None, status: str | None = None) -> dict: ...
    def delete_user(self, user_id: str) -> dict: ...
    def list_users(self, tenant_id: str | None = None) -> dict: ...
    def issue_token(self, agent_id: str, tenant_id: str, scopes: list[str]) -> dict: ...
    def revoke_token(self, token: str) -> dict: ...
    def list_tokens(self, tenant_id: str | None = None, agent_id: str | None = None) -> dict: ...
    def validate_token(self, token: str) -> dict | None: ...
    def register_asset_type(self, type: str, yaml_def: str) -> dict: ...
    def unregister_asset_type(self, type: str) -> dict: ...
    def list_asset_types(self) -> dict: ...
    def create_secret(self, tenant_id: str, key_name: str, value: str,
                      description: str = "", created_by: str = "") -> dict: ...
    def update_secret(self, tenant_id: str, key_name: str, value: str,
                      description: str = "") -> dict: ...
    def delete_secret(self, tenant_id: str, key_name: str) -> dict: ...
    def list_secrets(self, tenant_id: str) -> dict: ...
    def get_secret_values(self, tenant_id: str) -> dict: ...
    def log_secret_access(self, tenant_id: str, key_name: str,
                          accessed_by: str, task_id: str = "",
                          ray_job_id: str = "") -> None: ...
    def create_ray_job(self, job_id: str, tenant_id: str, agent_id: str,
                       skill_uri: str, job_name: str, entrypoint: str,
                       params: dict, task_id: str = "") -> dict: ...
    def update_ray_job_status(self, job_id: str, status: str,
                              ray_job_id: str = "", result_uri: str = "") -> dict: ...
    def get_ray_job(self, job_id: str) -> dict | None: ...
    def list_ray_jobs(self, tenant_id: str, status: str = "") -> dict: ...
    def health(self) -> bool: ...


class SQLComputePlugin(Protocol):
    def execute(self, sql: str, tables: dict[str, pa.Table] | None = None) -> list[dict]: ...
    def health(self) -> bool: ...


class DistributedComputePlugin(Protocol):
    def submit(self, func: str, args: dict) -> str: ...
    def status(self, job_id: str) -> dict: ...
    def result(self, job_id: str) -> Any: ...
    def submit_skill_job(self, skill_zip: bytes, job_name: str,
                         env_vars: dict[str, str], resources_override: dict,
                         job_id: str) -> str: ...
    def get_job_status(self, ray_job_id: str) -> dict: ...
    def cancel_job(self, ray_job_id: str) -> dict: ...
    def health(self) -> bool: ...


class EmbeddingPlugin(Protocol):
    @property
    def dim(self) -> int: ...
    def embed(self, texts: list[str]) -> list[list[float]]: ...
    def health(self) -> bool: ...


class MemoryPlugin(Protocol):
    def add(self, agent_id: str, tenant_id: str, messages: list[dict],
            metadata: dict | None = None, infer: bool = True,
            expiration_date: str | None = None,
            run_id: str | None = None) -> dict: ...
    def search(self, agent_id: str, tenant_id: str, query: str,
               filters: dict | None = None, top_k: int = 10,
               threshold: float = 0.1, run_id: str | None = None) -> list[dict]: ...
    def get(self, agent_id: str, tenant_id: str, memory_id: str) -> dict | None: ...
    def list_all(self, agent_id: str, tenant_id: str, filters: dict | None = None,
                 page: int = 1, page_size: int = 50,
                 run_id: str | None = None) -> dict: ...
    def update(self, agent_id: str, tenant_id: str, memory_id: str, content: str) -> dict: ...
    def delete(self, agent_id: str, tenant_id: str, memory_id: str) -> dict: ...
    def clear(self, agent_id: str, tenant_id: str, filters: dict | None = None,
              run_id: str | None = None) -> dict: ...
    def history(self, agent_id: str, tenant_id: str, memory_id: str) -> list[dict]: ...
    def health(self) -> bool: ...


class LLMPlugin(Protocol):
    def chat(self, messages: list[dict], model: str = "",
             temperature: float = 0.7, max_tokens: int = 0,
             **kwargs) -> dict: ...
    def embed(self, texts: list[str], model: str = "") -> list[list[float]]: ...
    def list_models(self) -> list[dict]: ...
    def health(self) -> bool: ...
